### ISSUE TITLE
Midterm-if Ready

### ISSUE THREAD

**Issue by kganser-matc** [madisoncollege-it-programs/python-scripting-kganser-matc#10]

**Comment by cethenmc** [comment]
I like the creativity of using a concept we did not learn in this class yet.  I assume you could not recall a method to extract the line number as requested.  What if the lines had gaps in IDs, weren't sorted, or theirIDss started with 1000?  Move Lanie Whiteland's record down between IDs 13 and 14, and your total would end up being 2427.  As a result of not extracting the line number and converting it to an int (which was a hint to help you know what you might use to extract), you will receive a score of 29/33
