### ISSUE TITLE
Week 12 Lab READY FOR GRADING

### ISSUE THREAD

**Issue by kganser-matc** [madisoncollege-it-programs/python-scripting-kganser-matc#14]

**Comment by cethenmc** [comment]
Many nicely done things in the code.  However, the chat client should continue to prompt me to type more until I type the word exit.  This tells me there is no while loop, as there should be.

The file transfer is pretty good.  However, when diffing the files, they are different.  The transferred file looks to still be in a byte array.

Recording a 6 out of 8.  **Please resubmit from this issue ticket or let me know if you intend to keep the 6 out of 8.**  Please reach out if you need a hand.

**Comment by kganser-matc** [comment]
Issues should be fixed

**Comment by cethenmc** [comment]
Fantastic on the chat!  The file transfer still looks a little off.  Upgraded score to 7 out of 8.  With your score on the final in, you do not need the next point.  I am certainly happy to walk through if you'd like and give you credit if you'd like.  Just reach out if you would like.

![image](https://user-images.githubusercontent.com/112707666/207424655-a2b4bfba-0d42-40c3-b76c-cc3526fee86f.png)
