### ISSUE TITLE
Final Exam - READY FOR GRADING

### ISSUE THREAD

**Issue by kganser-matc** [madisoncollege-it-programs/python-scripting-kganser-matc#17]

**Comment by cethenmc** [comment]
Hi, Kaden.  Very nice Final Project!

Lines 20 and 21 could have been achieved more efficiently.  You actually did not need to use the find function, if you desire to know, I am happy to walk through it.  Additionally, when using the formatted string you did not need to concatenate.  You could have removed the <<" + ">> and ended with the same result.  (-1 point)

Beautiful!  99 out of 100.
